/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the License governing permissions and limitations.
 */

#include <livekit/livekit.h>
#include <livekit/token_source.h>

#include <chrono>
#include <cstdlib>
#include <iostream>
#include <thread>

namespace {

bool runConnectedSession(livekit::Room& room) {
  auto local_participant = room.localParticipant().lock();
  if (!local_participant) {
    std::cerr << "Failed to get local participant\n";
    return false;
  }
  std::cout << "Local participant: " << local_participant->identity() << "\n";

  std::this_thread::sleep_for(std::chrono::seconds(2));

  if (!room.disconnect()) {
    std::cerr << "Failed to gracefully disconnect from room\n";
    return false;
  }

  std::cout << "Disconnected from room\n";
  return true;
}

bool literalTokenSourceConnect() {
  const char* url_env = std::getenv("LIVEKIT_URL");
  const char* token_env = std::getenv("LIVEKIT_TOKEN_A");
  if (url_env == nullptr || url_env[0] == '\0') {
    std::cerr << "LIVEKIT_URL not set\n";
    return false;
  }
  if (token_env == nullptr || token_env[0] == '\0') {
    std::cerr << "LIVEKIT_TOKEN_A not set\n";
    return false;
  }

  // Room and participant name/identity are encoded into the token generated by livekit-cli.
  auto token_source = livekit::LiteralTokenSource::fromValue(url_env, token_env);

  livekit::Room room;
  if (!room.connect(*token_source, livekit::RoomOptions())) {
    std::cerr << "Failed to connect to room\n";
    return false;
  }
  std::cout << "Connected to room: " << room.roomInfo().name << " (literal token source)\n";

  return runConnectedSession(room);
}

bool sandboxTokenSourceConnect() {
  const char* sandbox_id_env = std::getenv("LIVEKIT_SANDBOX_ID");
  if (sandbox_id_env == nullptr || sandbox_id_env[0] == '\0') {
    std::cerr << "LIVEKIT_SANDBOX_ID not set\n";
    return false;
  }

  // Sandbox token server: POSTs to cloud-api.livekit.io/api/v2/sandbox/connection-details
  // with X-Sandbox-ID set from LIVEKIT_SANDBOX_ID.
  auto token_source = livekit::SandboxTokenSource::fromSandboxId(sandbox_id_env);

  livekit::TokenRequestOptions options;
  options.participant_identity = "robot-a";

  options.agent_name = "token-source-agent";
  options.agent_metadata = R"({"greeting": "hello from cpp"})";

  livekit::Room room;
  if (!room.connect(*token_source, options, livekit::RoomOptions())) {
    std::cerr << "Failed to connect to room\n";
    return false;
  }
  std::cout << "Connected to room: " << room.roomInfo().name << " (sandbox token source)\n";

  return runConnectedSession(room);
}

} // namespace

int main() {
  livekit::initialize(livekit::LogLevel::Info);

  // Swap the active connect function below.
  // if (!literalTokenSourceConnect()) {
  if (!sandboxTokenSourceConnect()) {
    livekit::shutdown();
    return 1;
  }

  livekit::shutdown();
  return 0;
}
