/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the License governing permissions and limitations.
 */

#include <livekit/livekit.h>
#include <livekit/token_source.h>

#include <cctype>
#include <chrono>
#include <cstddef>
#include <cstdlib>
#include <iostream>
#include <string>
#include <thread>

namespace {

using namespace std::chrono_literals;

// How long to stay connected so participant join/leave events can be observed.
constexpr auto kObserveDuration = 5s;

/// Render a participant display name, falling back to "<unset>" when empty.
std::string displayName(const std::string& name) { return name.empty() ? "<unset>" : name; }

/// Standard one-line description of a participant (local or remote).
std::string formatParticipant(const livekit::Participant& participant) {
  return "identity=" + participant.identity() + ", name=" + displayName(participant.name());
}

/// Minimal delegate that logs remote participant join/leave activity.
class ParticipantLogDelegate : public livekit::RoomDelegate {
public:
  void onParticipantConnected(livekit::Room& /*room*/, const livekit::ParticipantConnectedEvent& event) override {
    if (event.participant == nullptr) {
      return;
    }
    std::cout << "Participant connected: " << formatParticipant(*event.participant) << "\n";
  }

  void onParticipantDisconnected(livekit::Room& /*room*/, const livekit::ParticipantDisconnectedEvent& event) override {
    if (event.participant == nullptr) {
      return;
    }
    std::cout << "Participant disconnected: identity=" << event.participant->identity() << "\n";
  }
};

void logRemoteParticipants(const livekit::Room& room) {
  const auto participants = room.remoteParticipants();
  std::cout << "Remote participants currently in room: " << participants.size() << "\n";
  for (const auto& participant_weak : participants) {
    if (const auto participant = participant_weak.lock()) {
      std::cout << "  - " << formatParticipant(*participant) << "\n";
    }
  }
}

bool runConnectedSession(livekit::Room& room) {
  const auto local_participant = room.localParticipant().lock();
  if (!local_participant) {
    std::cerr << "Failed to get local participant\n";
    return false;
  }
  std::cout << "Local participant info: " << formatParticipant(*local_participant) << "\n";

  logRemoteParticipants(room);

  // Stay connected briefly so participant join/leave events are surfaced.
  std::this_thread::sleep_for(kObserveDuration);
  logRemoteParticipants(room);

  if (!room.disconnect()) {
    std::cerr << "Failed to gracefully disconnect from room\n";
    return false;
  }

  std::cout << "Disconnected from room\n";
  return true;
}

bool literalTokenSourceConnect() {
  const char* url_env = std::getenv("LIVEKIT_URL");
  const char* token_env = std::getenv("LIVEKIT_TOKEN_A");
  if (url_env == nullptr || url_env[0] == '\0') {
    std::cerr << "LIVEKIT_URL not set\n";
    return false;
  }
  if (token_env == nullptr || token_env[0] == '\0') {
    std::cerr << "LIVEKIT_TOKEN_A not set\n";
    return false;
  }

  // Room and participant name/identity are encoded into the token generated by livekit-cli.
  auto token_source = livekit::LiteralTokenSource::fromValue(url_env, token_env);

  livekit::Room room;
  ParticipantLogDelegate delegate;
  room.setDelegate(&delegate);
  if (!room.connect(*token_source, livekit::RoomOptions())) {
    std::cerr << "Failed to connect to room\n";
    return false;
  }
  std::cout << "Connected to room: " << room.roomInfo().name << " (literal token source)\n";

  return runConnectedSession(room);
}

std::string trimWhitespace(const std::string& value) {
  std::size_t begin = 0;
  std::size_t end = value.size();
  while (begin < end && std::isspace(static_cast<unsigned char>(value[begin])) != 0) {
    ++begin;
  }
  while (end > begin && std::isspace(static_cast<unsigned char>(value[end - 1])) != 0) {
    --end;
  }
  return value.substr(begin, end - begin);
}

// Parses HTTP transport options for EndpointTokenSource from the environment.
//
// LIVEKIT_TOKEN_ENDPOINT_METHOD  - optional HTTP method (default POST).
// LIVEKIT_TOKEN_ENDPOINT_HEADERS - optional newline-separated "Name: Value" pairs,
//                                  e.g. "X-Sandbox-ID: my-id" or "Authorization: Bearer ...".
livekit::TokenEndpointOptions endpointOptionsFromEnv() {
  livekit::TokenEndpointOptions options;

  if (const char* method_env = std::getenv("LIVEKIT_TOKEN_ENDPOINT_METHOD");
      method_env != nullptr && method_env[0] != '\0') {
    options.method = method_env;
  }

  const char* headers_env = std::getenv("LIVEKIT_TOKEN_ENDPOINT_HEADERS");
  if (headers_env == nullptr || headers_env[0] == '\0') {
    return options;
  }

  const std::string headers_text = headers_env;
  std::size_t start = 0;
  while (start <= headers_text.size()) {
    const std::size_t newline = headers_text.find('\n', start);
    const std::string line =
        headers_text.substr(start, newline == std::string::npos ? std::string::npos : newline - start);
    const std::size_t colon = line.find(':');
    if (colon != std::string::npos) {
      const std::string name = trimWhitespace(line.substr(0, colon));
      const std::string value = trimWhitespace(line.substr(colon + 1));
      if (!name.empty()) {
        options.headers[name] = value;
      }
    }
    if (newline == std::string::npos) {
      break;
    }
    start = newline + 1;
  }

  return options;
}

bool endpointTokenSourceConnect() {
  std::string endpoint_url;
  if (const char* endpoint_env = std::getenv("LIVEKIT_TOKEN_ENDPOINT");
      endpoint_env != nullptr && endpoint_env[0] != '\0') {
    endpoint_url = endpoint_env;
  } else {
    const char* port_env = std::getenv("TOKEN_SERVER_PORT");
    const char* port = (port_env != nullptr && port_env[0] != '\0') ? port_env : "3000";
    endpoint_url = std::string("http://127.0.0.1:") + port + "/createToken";
  }

  auto endpoint_options = endpointOptionsFromEnv();
  std::cout << "Endpoint token source: " << endpoint_options.method << " " << endpoint_url << " ("
            << endpoint_options.headers.size() << " custom header(s))\n";

  auto token_source = livekit::EndpointTokenSource::fromUrl(endpoint_url, std::move(endpoint_options));

  livekit::TokenRequestOptions options;
  options.participant_identity = "robot-a";

  livekit::Room room;
  ParticipantLogDelegate delegate;
  room.setDelegate(&delegate);
  if (!room.connect(*token_source, options, livekit::RoomOptions())) {
    std::cerr << "Failed to connect to room\n";
    return false;
  }
  std::cout << "Connected to room: " << room.roomInfo().name << " (endpoint token source)\n";

  return runConnectedSession(room);
}

bool sandboxTokenSourceConnect() {
  const char* sandbox_id_env = std::getenv("LIVEKIT_SANDBOX_ID");
  if (sandbox_id_env == nullptr || sandbox_id_env[0] == '\0') {
    std::cerr << "LIVEKIT_SANDBOX_ID not set\n";
    return false;
  }

  // Sandbox token server: POSTs to cloud-api.livekit.io/api/v2/sandbox/connection-details
  // with X-Sandbox-ID set from LIVEKIT_SANDBOX_ID.
  auto token_source = livekit::SandboxTokenSource::fromSandboxId(sandbox_id_env);

  livekit::TokenRequestOptions options;
  options.participant_identity = "robot-a";

  // Optional agent dispatch: when LIVEKIT_AGENT_NAME is set, the request embeds
  // room_config.agents so the token server dispatches a named agent into the room.
  if (const char* agent_name_env = std::getenv("LIVEKIT_AGENT_NAME");
      agent_name_env != nullptr && agent_name_env[0] != '\0') {
    options.agent_name = agent_name_env;
    if (const char* agent_metadata_env = std::getenv("LIVEKIT_AGENT_METADATA");
        agent_metadata_env != nullptr && agent_metadata_env[0] != '\0') {
      options.agent_metadata = agent_metadata_env;
    }
    std::cout << "Requesting sandbox token with agent dispatch: agent_name=" << *options.agent_name << "\n";
  }

  livekit::Room room;
  ParticipantLogDelegate delegate;
  room.setDelegate(&delegate);
  if (!room.connect(*token_source, options, livekit::RoomOptions())) {
    std::cerr << "Failed to connect to room\n";
    return false;
  }
  std::cout << "Connected to room: " << room.roomInfo().name << " (sandbox token source)\n";

  return runConnectedSession(room);
}

} // namespace

int main() {
  livekit::initialize(livekit::LogLevel::Info);

  // Swap the active connect function below to exercise a given token source.
  // if (!literalTokenSourceConnect()) {
  // if (!endpointTokenSourceConnect()) {
  if (!sandboxTokenSourceConnect()) {
    livekit::shutdown();
    return 1;
  }

  livekit::shutdown();
  return 0;
}
