# cmake/sdl3.cmake
include(FetchContent)

# Only fetch/build SDL3 once, even if this file is included multiple times
if (NOT TARGET SDL3::SDL3)
    # Prevent SDL3 from polluting our lib directory
    set(SDL_INSTALL OFF CACHE BOOL "Disable SDL3 install" FORCE)
    set(SDL_SHARED ON CACHE BOOL "Build shared SDL3" FORCE)
    
    # Save current output directories
    set(_SAVE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
    set(_SAVE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
    set(_SAVE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
    
    # Set SDL3 to build into its own subdirectory
    set(SDL3_OUTPUT_DIR ${CMAKE_BINARY_DIR}/_deps/sdl3-build)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${SDL3_OUTPUT_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${SDL3_OUTPUT_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${SDL3_OUTPUT_DIR})
    
    # For multi-config generators (Visual Studio), also set per-config directories
    foreach(CONFIG_TYPE Debug Release RelWithDebInfo MinSizeRel)
        string(TOUPPER ${CONFIG_TYPE} CONFIG_TYPE_UPPER)
        set(_SAVE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
        set(_SAVE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
        set(_SAVE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
        
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${SDL3_OUTPUT_DIR})
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${SDL3_OUTPUT_DIR})
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${SDL3_OUTPUT_DIR})
    endforeach()
    
    FetchContent_Declare(
        SDL3
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG        release-3.2.26
    )

    FetchContent_MakeAvailable(SDL3)
    
    # Restore output directories
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${_SAVE_ARCHIVE_OUTPUT_DIRECTORY})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${_SAVE_LIBRARY_OUTPUT_DIRECTORY})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${_SAVE_RUNTIME_OUTPUT_DIRECTORY})
    
    foreach(CONFIG_TYPE Debug Release RelWithDebInfo MinSizeRel)
        string(TOUPPER ${CONFIG_TYPE} CONFIG_TYPE_UPPER)
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${_SAVE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${_SAVE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER} ${_SAVE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE_UPPER}})
    endforeach()
endif()
