blank_issues_enabled: false
contact_links:
  - name: Developer Community
    url: https://community.livekit.io/
    about: Ask questions, suggest improvements, and discuss contributions
  - name: LiveKit Documentation
    url: https://docs.livekit.io/
    about: Check the docs before filing an issue