#!/usr/bin/env bash
#
# Copyright 2026 LiveKit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(cd "${script_dir}/.." && pwd -P)"

usage() {
  cat <<'EOF'
Usage: ./scripts/generate-docs.sh [--version VERSION]

Build Doxygen HTML docs with a visible project version.

Options:
  --version VERSION
        Version to display in generated docs. Accepts either "0.1.0" or
        "v0.1.0"; the rendered Doxygen PROJECT_NUMBER will include "v".
  -h, --help
        Show this help and exit.

When --version is omitted, the script uses LIVEKIT_DOXYGEN_PROJECT_NUMBER if
already set. Otherwise it derives a local version from git describe.
EOF
}

version_arg=""

while (($#)); do
  case "$1" in
    --version)
      shift
      if (($# == 0)); then
        echo "ERROR: --version requires a value" >&2
        exit 2
      fi
      version_arg="$1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v doxygen >/dev/null 2>&1; then
  echo "ERROR: doxygen not found in PATH." >&2
  echo "Install: brew install doxygen graphviz  (macOS)" >&2
  echo "         apt install doxygen graphviz   (Linux)" >&2
  exit 1
fi

project_number="${LIVEKIT_DOXYGEN_PROJECT_NUMBER:-}"

if [[ -n "$version_arg" ]]; then
  version="${version_arg#v}"
  project_number="v${version}"
elif [[ -z "$project_number" ]]; then
  if git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    described="$(git -C "$repo_root" describe --tags --dirty --always 2>/dev/null || true)"
  else
    described=""
  fi

  # git describe emits "<tag>-<n>-g<sha>[-dirty]"
  # Strip unneeded "g" so it's easier to read
  if [[ "$described" =~ ^(.+-[0-9]+)-g([0-9a-f]+)(.*)$ ]]; then
    described="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
  fi

  if [[ -z "$described" ]]; then
    project_number="v0.0.0-dev"
  elif [[ "$described" == v* ]]; then
    project_number="$described"
  else
    project_number="v0.0.0-dev+${described}"
  fi
elif [[ "$project_number" != v* ]]; then
  project_number="v${project_number}"
fi

if [[ -z "$project_number" ]]; then
  echo "ERROR: derived Doxygen project number is empty" >&2
  exit 1
fi

if [[ "$project_number" =~ [[:space:]] ]]; then
  echo "ERROR: Doxygen project number contains whitespace: '$project_number'" >&2
  exit 1
fi

echo "==> Building Doxygen docs with PROJECT_NUMBER=${project_number}"
cd "$repo_root"

# Build a Doxygen-only mainpage derived from README.md so README can remain
# GitHub-optimized while docs rendering stays strict under WARN_AS_ERROR.
mainpage_rel="docs/doxygen/README.doxygen.md"
mainpage_tmp="${repo_root}/${mainpage_rel}"
doxyfile_tmp="$(mktemp "${TMPDIR:-/tmp}/livekit-doxyfile.XXXXXX")"
cleanup() {
  rm -f "$mainpage_tmp" "$doxyfile_tmp"
}
trap cleanup EXIT

python3 - "$repo_root/README.md" "$mainpage_tmp" <<'PY'
import pathlib
import re
import sys

readme_path = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])
text = readme_path.read_text(encoding="utf-8")

# Doxygen's Markdown parser rejects <picture>/<source>. Replace the banner block
# with a docs-only dark/light pair controlled by CSS in custom.css.
banner_replacement = """<!--BEGIN_BANNER_IMAGE-->

<div class="doxygen-readme-banner">
  <img class="doxygen-banner-light" alt="The LiveKit icon, the name of the repository and some sample code in the background." src="https://raw.githubusercontent.com/livekit/client-sdk-cpp/main/.github/banner_light.png">
  <img class="doxygen-banner-dark" alt="The LiveKit icon, the name of the repository and some sample code in the background." src="https://raw.githubusercontent.com/livekit/client-sdk-cpp/main/.github/banner_dark.png">
</div>

<!--END_BANNER_IMAGE-->"""
text = re.sub(
    r"<!--BEGIN_BANNER_IMAGE-->.*?<!--END_BANNER_IMAGE-->",
    banner_replacement,
    text,
    flags=re.DOTALL,
)

out_path.write_text(text, encoding="utf-8")
PY

cp "$repo_root/docs/doxygen/Doxyfile" "$doxyfile_tmp"
{
  echo ""
  echo "# Local override generated by scripts/generate-docs.sh"
  echo "INPUT = include/livekit ${mainpage_rel} docs/README.md docs/building.md docs/authentication.md docs/reconnection.md docs/logging.md docs/tracing.md docs/testing.md docs/tools.md"
  echo "USE_MDFILE_AS_MAINPAGE = ${mainpage_rel}"
} >>"$doxyfile_tmp"

LIVEKIT_DOXYGEN_PROJECT_NUMBER="$project_number" doxygen "$doxyfile_tmp"

docs_index="${repo_root}/docs/doxygen/html/index.html"

echo "==> Docs written to ${docs_index}"

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  echo "project_number=${project_number}" >>"$GITHUB_OUTPUT"
fi
